### PR TITLE
COMPLETE V12 rewrite

### PR DESCRIPTION
**Pull request by Noorquacker**
Yeah, it's rewritten.

### CODE REVIEW

**Comment by Mitchell12345MB** [comment]
You realize this isn't a competition. I don't even code any more.

Other than that, thank you.

**Review by Mitchell12345MB — DISMISSED** [review]

**Comment by Mitchell12345MB** [comment]
Oi, how about you be manager of my plugin since I really don't code it any more?

**Comment by Noorquacker** [comment]
I'm up for manager. I wasn't really trying to make it a competition, just a major improvement.

**Comment by Mitchell12345MB** [comment]
Okay great! I'll make sure to add you to the manager position, and keep your name as one of the authors in the plugin itself. I'm going to have to think about this some more, but I'm going to update the plugin when I get around to it. In the mean time, try to figure out a way to make our own particle affects, and then we'll go from there.

**Comment by Mitchell12345MB** [comment]
Damn this is old. Think i should delete it?

**Comment by Noorquacker** [comment]
> 
> 
> Damn this is old. Think i should delete it?

Idk, it doesn't really need any maintenance to keep the source up, it's the first thing that shows up on Google.
Plus it's the most popular plugin that lists me as the author

**Comment by Mitchell12345MB** [comment]
So, the guy who made the ssj mod died, and there doesnt seem to be a new update for more modern servers

**Comment by Mitchell12345MB** [comment]
Want to make this into a mod?

**Comment by Noorquacker** [comment]
Not really tbh. I'm terrible at working with Forge's mdk since I got used to Bukkit's way, and a plugin would probably reach more people, and it doesn't need to be updated as much

**Pull request merged**
